name: CICD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: install AWS CLI
        run: | 
          pwd
          ls -lhrt
      
      - name: create S3 bucket
        run: |
          aws s3 mb s3://CICD

      - name: upload file in s3 bucket
        run: |
          aws s3 cp cloudfront.yml s3://CICD 

      - name: create stack
        run: |
          aws cloudformation create-stack --stack-name CICD --template-url s3://CICD/cloudfront.yml


