name: CICD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: install AWS CLI
        run: | 
          pwd
          ls -lhrt
          cat cloudformation.yml


